kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:20-slim
    volumes:
      - name: cache
        path: /pnpm/store
    environment:
      PNPM_HOME: /pnpm
      PATH: /pnpm:/usr/local/bin:/usr/bin:/bin
    commands:
      - corepack enable && corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /pnpm/store
      - pnpm install --frozen-lockfile

  - name: lint
    image: node:20-slim
    volumes:
      - name: cache
        path: /pnpm/store
    environment:
      PNPM_HOME: /pnpm
      PATH: /pnpm:/usr/local/bin:/usr/bin:/bin
    commands:
      - corepack enable && corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /pnpm/store
      - pnpm lint

  - name: type-check
    image: node:20-slim
    volumes:
      - name: cache
        path: /pnpm/store
    environment:
      PNPM_HOME: /pnpm
      PATH: /pnpm:/usr/local/bin:/usr/bin:/bin
    commands:
      - corepack enable && corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /pnpm/store
      - pnpm type-check

  - name: build
    image: node:20-slim
    volumes:
      - name: cache
        path: /pnpm/store
    environment:
      PNPM_HOME: /pnpm
      PATH: /pnpm:/usr/local/bin:/usr/bin:/bin
    commands:
      - corepack enable && corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /pnpm/store
      - pnpm build

  - name: deploy
    image: drillster/drone-rsync
    settings:
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_ssh_key
      hosts:
        - blog.tjausbj.com.cn
      source: dist/
      target: /var/www/blog-website
      recursive: true
      delete: true
    when:
      event:
        - push
      branch:
        - master
        - main

trigger:
  event:
    - push
    - pull_request

volumes:
  - name: cache
    temp: {}
